name: notify-release
on:
  workflow_dispatch:
  
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Release Notes
        run: |
          RELEASE_JSON=$(curl -s https://api.github.com/repos/olafkotur/switch-releases/releases/latest)
          RELEASE_NOTES_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name == "release-notes.md") | .browser_download_url')

          curl -LO $RELEASE_NOTES_URL
          echo "RELEASE_NOTES=$(grep -o '^- .*' release-notes.md | sed -e 's/^- //' | tr '\n' '\n')" >> $GITHUB_ENV

      - name: Send Message
        run: |
          BODY=$(echo "$RELEASE_NOTES" | sed -e 's/"/\\"/g')
          PAYLOAD="{ \"content\": \"$BODY\" }"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.NOTIFY_URL }}
