name: notify-release
on:
  workflow_dispatch:
  
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        run: |
          RELEASE_JSON=$(curl -s https://api.github.com/repos/olafkotur/switch-releases/releases/latest)
          RELEASE_NOTES_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name == "release-notes.txt") | .browser_download_url')

          curl -LO $RELEASE_NOTES_URL
          RELEASE_NOTES=$(<release-notes.txt)
          PAYLOAD="{ \"content\": \"$RELEASE_NOTES\" }"

          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.NOTIFY_URL }}
