name: update-release

on:
  release:
    types: [published]

jobs:
  update-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      BRANCH_NAME: release-${{ github.event.release.tag_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Release
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

          node index.js ${{ env.RELEASE_TAG }}

          git config --local user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --local user.name "${{ secrets.AUTHOR_USERNAME }}"

          git add .
          git commit -m "Update release files"
          git push origin ${{ env.BRANCH_NAME }}

          # create a new pull request
          PR_TITLE="Release ${{ env.RELEASE_TAG }}"
          PR_BODY="Automated changes for release ${{ env.RELEASE_TAG }}"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.repository }}"
          BASE_BRANCH="main"

          echo "PR_TITLE: Release ${{ env.RELEASE_TAG }}"
          echo "PR_BODY: Automated changes for release ${{ env.RELEASE_TAG }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "REPO_OWNER: ${{ github.repository_owner }}"
          echo "REPO_NAME: ${{ github.repository }}"
          echo "BASE_BRANCH: main"
          

          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "'"$PR_TITLE"'",
              "body": "'"$PR_BODY"'",
              "head": "'"$REPO_OWNER"':'"$env.BRANCH_NAME"'",
              "base": "'"$BASE_BRANCH"'"
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls"
