name: update-release

on:
  release:
    types: [published]

jobs:
  update-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      BRANCH_NAME: release-${{ github.event.release.tag_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Release
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

          node index.js ${{ env.RELEASE_TAG }}

          git config --local user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --local user.name "${{ secrets.AUTHOR_USERNAME }}"

          git add .
          git commit -m "Update release files"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Wait for Branch
        run: |
          echo https://api.github.com/repos/${{ secrets.AUTHOR_USERNAME }}/${{ github.repository }}/pulls
          sleep 15

      - name: Create Pull Request
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "title": "Release ${{ env.RELEASE_TAG }}",
              "body": "Automated changes for release ${{ env.RELEASE_TAG }}",
              "head": "${{ env.BRANCH_NAME }}",
              "base": "main"
            }' \
            "https://api.github.com/repos/${{ secrets.AUTHOR_USERNAME }}/${{ github.repository }}/pulls"